baseURL = "https://www.true1984.com/"
languageCode = "en-us"
title = "Building a More Perfect World!"
theme = "mainroad"
author = "Stephard Loudwater"
[markup.goldmark.renderer] safe = true # Allow HTML in md files
hardWraps = true